ARG NODE_VERSION=18

FROM node:$NODE_VERSION-buster AS base

WORKDIR /app

FROM base AS builder

COPY package.json .
COPY yarn.lock .
COPY lerna.json .
COPY packages ./packages


RUN yarn install
RUN yarn lerna bootstrap
RUN cd packages/client && yarn link && cd ../..
RUN cd packages/server && yarn link client && cd ../..

RUN yarn build --scope=client
RUN yarn build --scope=server

EXPOSE $SERVER_PORT
CMD [ "node", "/app/packages/server/dist/index.js" ]
