version: '3.9'

services:
  server:
    env_file:
      - .env
    image: cr.yandex/crpgh2ol253ukr39r3c9/prakticum-server:v9
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    platform: linux/amd64
    depends_on: [postgres]
  postgres:
    container_name: postgres_container
    env_file:
      - .env
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    pull_policy: always
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT:-5050}:80'
volumes:
  pgadmin:
