version: '3.9'

services:
  server:
    image: cr.yandex/crpgh2ol253ukr39r3c9/prakticum-server:1.0
    restart: always
    platform: linux/amd64
    environment:
        SERVER_PORT: 3000
        CLIENT_PORT: 3000
        CLIENT_URL: http://158.160.75.93:3000
        SERVER_URL: http://158.160.75.93:3000/api/forum
        NODE_ENV: production
        POSTGRES_PORT: 6432
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres_admin
        POSTGRES_DB: slytherin_db
        POSTGRES_HOST: rc1d-zywj4h0x5c3mcb6y.mdb.yandexcloud.net
    networks:
      - backend
  nginx:
    image: nginx
    restart: always
    platform: linux/amd64
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontend
      - backend
configs:
  nginx_config:
    file: ./nginx/nginx.conf
  # postgres:
  #   container_name: postgres_container
  #   env_file:
  #     - .env
  #   image: postgres:14
  #   ports:
  #     - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - ./tmp/pgdata:/var/lib/postgresql/data
  #   pull_policy: always
networks:
  frontend:
    external: true
  backend:
    external: false