version: '3.9'

services:
  server:
    image: cr.yandex/crpgh2ol253ukr39r3c9/prakticum-server:1.0
    restart: always
    platform: linux/amd64
    environment:
      SERVER_PORT: 3000
      CLIENT_PORT: 3000
      CLIENT_URL: http://158.160.75.93:3000/
      SERVER_URL: http://158.160.75.93:3000/api/forum
      NODE_ENV: production
      POSTGRES_PORT: 6432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: slytherin_db
      POSTGRES_HOST: rc1d-zywj4h0x5c3mcb6y.mdb.yandexcloud.net
    networks:
      - backend
  nginx:
    image: nginx
    restart: always
    platform: linux/amd64
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
        --email aikei3@yandex.ru --agree-tos --no-eff-email
        -d slytherin.ya-praktikum.tech
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
configs:
  nginx_config:
    file: ./nginx/nginx.conf

networks:
  frontend:
    external: true
  backend:
    external: false